<MainMenu>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: 189/255, 158/255, 219/255, 1
            Rectangle:
                size: self.size
                pos: self.pos
        Label:
            text: 'Note Attack'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '70sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.5, 'center_y': 0.8}  

        Button:
            text: 'Start Game'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '31sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}  
            on_press: root.transition_state(1)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)

        Button:
            text: 'Rules'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.45}  
            on_press: root.transition_state(2)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)

        Button:
            text: 'Settings'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.3} 
            on_press: root.transition_state(3)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)
  
        Button:
            text: 'Leaderboard'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.15}
            on_press: root.transition_state(4)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)

<Rules>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: 189/255, 158/255, 219/255, 1
            Rectangle:
                size: self.size
                pos: self.pos
        Label:
            text: 'Rules'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '70sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.5, 'center_y': 0.88}  
        Label:
            text: "1. Plug your device into a MIDI\n instrument.\n\n2. Click start and play the notes \nthat appear on your screen \naccordingly to shoot the enemies.\n\n3. You gain points for each enemy \nyou hit and the game ends if an \nenemy reaches you.\n\n4.Adjust your difficulty and \nchange themes in the settings."
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '25sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.5, 'center_y': 0.52}  
        Button:
            text: 'Back to Menu'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.13}  
            on_press: root.transition_state(0)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)

<Settings>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: 189/255, 158/255, 219/255, 1
            Rectangle:
                size: self.size
                pos: self.pos
        Button:
            text: 'Back to Menu'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.13}  
            on_press: root.transition_state(0)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)

        Button:

            text: 'Customisation'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '35sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.8}  
            on_press: root.transition_state(5)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)
        
        Button:
            text: 'Hard'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}  
            on_press: root.set_difficulty(2)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: root.hard_color
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)
        Button:
            text: 'Medium'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.5} 
            on_press: root.set_difficulty(1)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: root.medium_color
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)
        Button:
            text: 'Easy'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            on_press: root.set_difficulty(0)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: root.easy_color
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)

<Customisation>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: 189/255, 158/255, 219/255, 1
            Rectangle:
                size: self.size
                pos: self.pos
        Label:
            text: 'Customisation'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '50sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.5, 'center_y': 0.8} 
        Spinner:
            text: 'Themes'
            values: ['Pink', 'Blue', 'Red', 'Orange', 'Green', 'Outer Space']
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '35sp'
            color: 95/255, 29/255, 120/255, 1
            width: '300sp'
            height: '70sp'
            size_hint: None, None
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            background_color: 0,0,0,0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)
            option_cls: 'CustomSpinnerOption'


        Spinner:
            text: 'Skins'
            values: ['Pink', 'Blue', 'Red', 'Orange', 'Green', 'Mars']
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '35sp'
            color: 95/255, 29/255, 120/255, 1
            width: '300sp'
            height: '70sp'
            size_hint: None, None
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            background_color: 0,0,0,0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)
            option_cls: 'CustomSpinnerOption'

        Button:
            text: 'Back to Menu'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '35sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.13}  
            on_press: root.transition_state(0)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)
                    
<CustomSpinnerOption@SpinnerOption>:
    font_name: 'Assets/CourierPrime-Regular.ttf'
    font_size: '30sp'
    color: 95/255, 29/255, 120/255, 1
    background_color: 0, 0, 0, 0
    canvas.before:
        Color:
            rgba: 146/255, 125/255, 168/255, 1
        Rectangle:
            size: self.size
            pos: self.pos
        Color:
            rgba: 95/255, 29/255, 120/255, 1
        Line:
            width: 3
            rectangle: (self.x, self.y, self.width, self.height)

<Leaderboard>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: 189/255, 158/255, 219/255, 1
            Rectangle:
                size: self.size
                pos: self.pos
        Button:
            text: 'Back to Menu'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.5, 'center_y': 0.13}  
            on_press: root.transition_state(0)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)
        Label:
            text: 'Easy Leaderboard'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.44, 'center_y': 0.92}  
        Label:
            text: "1:\n2:\n3:\n4:\n5:"
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '25sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.2, 'center_y': 0.8} 
        Label:
            text: 'Medium Leaderboard'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.47, 'center_y': 0.67} 
        Label:
            text: "1:\n2:\n3:\n4:\n5:"
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '25sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.2, 'center_y': 0.55} 
        Label:
            text: 'Hard Leaderboard'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.44, 'center_y': 0.42} 
        Label:
            text: "1:\n2:\n3:\n4:\n5:"
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '25sp'
            color: 95/255, 29/255, 120/255, 1
            pos_hint: {'center_x': 0.2, 'center_y': 0.3} 

<GamePlay>:
    FloatLayout:
        canvas.before:
            Color:
                rgba: 189/255, 158/255, 219/255, 1
            Rectangle:
                size: self.size
                pos: self.pos

        Character:
            size_hint: None, None
            size: 100, 100
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            canvas:
                Color:
                    rgba: 95/255, 29/255, 120/255, 11
                Ellipse:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 0, 0, 0, 1
                Line:
                    width: 3
                    ellipse: (self.x, self.y, self.width, self.height)

        Button:
            text: 'Back to Menu'
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.65, 'center_y': 0.9}  
            on_press: root.transition_state(0)
            background_color: 0, 0, 0, 0
            canvas.before:
                Color:
                    rgba: 151/255, 104/255, 196/255, 1
                Rectangle:
                    size: self.size
                    pos: self.pos
                Color:
                    rgba: 95/255, 29/255, 120/255, 1
                Line:
                    width: 3
                    rectangle: (self.x, self.y, self.width, self.height)

        Label:
            text: 'score: ' + root.score
            font_name: 'Assets/CourierPrime-Regular.ttf'
            font_size: '30sp'
            color: 95/255, 29/255, 120/255, 1
            size_hint: None, None
            width: '300sp'
            height: '70sp'
            pos_hint: {'center_x': 0.2, 'center_y': 0.05}  


<Enemies>:
    canvas:
        Color:
            rgba: 1, 0, 0, 1
        Ellipse:
            size: self.size
            pos: self.pos
        Color:
            rgba: 0, 0, 0, 1
        Line:
            width: 3
            ellipse: (self.x, self.y, self.width, self.height)
    Label:
        text: root.note
        font_name: 'Assets/CourierPrime-Regular.ttf'
        size_hint: None, None
        size: self.size
        pos: root.pos
        color: 1, 1, 1, 1  
        font_size: '35sp'
        text_size: self.size
        halign: 'center'
        valign: 'middle'
            